}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
} */
char getme8() {
	return 'w';
}
/*
void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}*/
char getme9() {
	return 'n';
}
/*
void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}*/
char getme10() {
	return 'a';
}
/*
void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}*/
char getme11() {
	return 'g';
}
/*
void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}*/
char getme12()
{
	return 'e';
}
/*
void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}*/
int main() {
	printf("M");
	printf("Y");
	printf(" ");
	printf("P");
	printf("A");
	printf("S");
	printf("S");
	printf("W");
	printf("O");
	printf("R");
	printf("D");
	printf(" ");
	printf("I");
	printf("S");
	printf(":");
	printf(" ");
	printf("%c",getme1());
	printf("%c",getme2());
	printf("%c",getme3());
	printf("%c",getme4());
	printf("%c",getme5());
	printf("%c",getme6());
	printf("%c",getme7());
	printf("%c",getme8());
	printf("%c",getme9());
	printf("%c",getme10());
	printf("%c",getme11());
	printf("%c",getme12());
	printf("\n");
	printf("Now SHA-256 it and submit");
}
/*
void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}void useless() {
	printf("Hahahaha Got you!!!\n");
}
*/
//file750